model:
  backbone: "resnet50"
  pretrained: true

data:
  train_path: "data/processed/train"
  val_path: "data/processed/val"
  test_path: "data/processed/test"
  temporal_length: 16
  image_size: [640, 640]
  batch_size: 8
  num_workers: 4

training:
  num_epochs: 100
  lambda_bbox: 1.0
  lambda_obj: 1.0
  lambda_activity: 1.0
  grad_clip: 1.0
  patience: 10

optimizer:
  name: "Adam"
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  T_0: 10
  T_mult: 2
  eta_min: 0.00001

augmentation:
  horizontal_flip_prob: 0.5
  vertical_flip_prob: 0.5
  rotation_range: [-30, 30]
  brightness_range: [0.8, 1.2]
  contrast_range: [0.8, 1.2]
  saturation_range: [0.8, 1.2]
  hue_range: [-0.1, 0.1]

inference:
  confidence_threshold: 0.5
  nms_threshold: 0.45
  activity_smoothing_window: 5

logging:
  use_wandb: true
  wandb_project: "rabere_detection"
  log_dir: "logs"
  checkpoint_dir: "models/checkpoints"
  log_interval: 100

system:
  seed: 42
  device: "cuda"
  precision: "mixed"  # Options: float32, float16, mixed
  distributed: false
  num_gpus: 1 