apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.28.0
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServer:
  extraArgs:
    enable-admission-plugins: NodeRestriction,PodSecurityPolicy
    audit-log-path: /var/log/kubernetes/audit.log
    audit-log-maxage: "30"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "100"
controllerManager:
  extraArgs:
    node-monitor-period: "4s"
    node-monitor-grace-period: "16s"
    pod-eviction-timeout: "30s"
scheduler:
  extraArgs:
    address: 0.0.0.0
etcd:
  local:
    dataDir: /var/lib/etcd 